#include "../base.h"
#include "../../Array/Array.h"
#include "../../Autoarr/Autoarr.h"
#include "../../SearchTree/SearchTree.h"
#include "../../Hashtable/Hashtable.h"
#include "../../String/StringBuilder.h"
#include "base_toString.h"

void ktDescriptors_initKerepTypes(){
    // null
    __kt_register("Null", sizeof(NULL), NULL, NULL);
    ktid_Null=ktid_last;
    // base types
    kt_register(char,    NULL, __toString_char);
    kt_register(bool,    NULL, __toString_bool);
    kt_register(f32, NULL, __toString_f32);
    kt_register(f64, NULL, __toString_f64);
    kt_register(i8,    NULL, __toString_i8);
    kt_register(u8,   NULL, __toString_u8);
    kt_register(i16,   NULL, __toString_i16);
    kt_register(u16,  NULL, __toString_u16);
    kt_register(i32,   NULL, __toString_i32);
    kt_register(u32,  NULL, __toString_u32);
    kt_register(i64,   NULL, __toString_i64);
    kt_register(u64,  NULL, __toString_u64);
    
    // ktDescriptor
    kt_register(ktDescriptor, NULL, NULL);


    // base type arrays
    kt_register(Array_char,    (freeMembers_t)Array_char_free, NULL);
    kt_register(Array_bool,    (freeMembers_t)Array_bool_free, NULL);
    kt_register(Array_f32, (freeMembers_t)Array_f32_free, NULL);
    kt_register(Array_f64, (freeMembers_t)Array_f64_free, NULL);
    kt_register(Array_i8,    (freeMembers_t)Array_i8_free, NULL);
    kt_register(Array_u8,   (freeMembers_t)Array_u8_free, NULL);
    kt_register(Array_i16,   (freeMembers_t)Array_i16_free, NULL);
    kt_register(Array_u16,  (freeMembers_t)Array_u16_free, NULL);
    kt_register(Array_i32,   (freeMembers_t)Array_i32_free, NULL);
    kt_register(Array_u32,  (freeMembers_t)Array_u32_free, NULL);
    kt_register(Array_i64,   (freeMembers_t)Array_i64_free, NULL);
    kt_register(Array_u64,  (freeMembers_t)Array_u64_free, NULL);

    // base type autoarrs
    kt_register(Autoarr_char,    ____Autoarr_free_char, NULL);
    kt_register(Autoarr_bool,    ____Autoarr_free_bool, NULL);
    kt_register(Autoarr_f32, ____Autoarr_free_f32, NULL);
    kt_register(Autoarr_f64, ____Autoarr_free_f64, NULL);
    kt_register(Autoarr_i8,    ____Autoarr_free_i8, NULL);
    kt_register(Autoarr_u8,   ____Autoarr_free_u8, NULL);
    kt_register(Autoarr_i16,   ____Autoarr_free_i16, NULL);
    kt_register(Autoarr_u16,  ____Autoarr_free_u16, NULL);
    kt_register(Autoarr_i32,   ____Autoarr_free_i32, NULL);
    kt_register(Autoarr_u32,  ____Autoarr_free_u32, NULL);
    kt_register(Autoarr_i64,   ____Autoarr_free_i64, NULL);
    kt_register(Autoarr_u64,  ____Autoarr_free_u64, NULL);

    // Unitype
    kt_register(Unitype,         __UnitypePtr_free,         NULL);
    kt_register(Array_Unitype,  __Array_Unitype_free_, NULL);
    kt_register(Autoarr_Unitype, ____Autoarr_free_Unitype_, NULL);
    // replacing autogenerated freear() function to custom 
    Autoarr_Unitype* _uar=Autoarr_create(Unitype, 1, 1);
    _uar->functions->freear=__Autoarr_free_Unitype_;
    Autoarr_free(_uar, true);

    // SearchTreeNode
    kt_register(STNode, __STNode_free, NULL);

    // KeyValuePair
    kt_register(KVPair, __KVPair_free, NULL);
    kt_register(Autoarr_KVPair, ____Autoarr_free_KVPair_, NULL);
    // replacing autogenerated freear() function to custom 
    Autoarr_KVPair* _kvpar=Autoarr_create(KVPair, 1, 1);
    _kvpar->functions->freear=__Autoarr_free_KVPair_;
    Autoarr_free(_kvpar, true);

    // Hashtable
    kt_register(Hashtable, __Hashtable_free, NULL);

    // string
    kt_register(string, NULL, NULL);
    kt_register(Array_string,   (freeMembers_t)Array_string_free, NULL);
    kt_register(Autoarr_string, ____Autoarr_free_string, NULL);
    // StringBuilder
    kt_register(StringBuilder, __StringBuilder_free, NULL);
}
