#include "Autoarr.h"

Autoarr_define(char)
Autoarr_define(bool)
Autoarr_define(f32)
Autoarr_define(f64)
Autoarr_define(u8)
Autoarr_define(i8)
Autoarr_define(u16)
Autoarr_define(i16)
Autoarr_define(u32)
Autoarr_define(i32)
Autoarr_define(u64)
Autoarr_define(i64)
Autoarr_define(Pointer)
