#include "base.h"
#include "../Autoarr/Autoarr.h"
#include "../SearchTree/SearchTree.h"
#include "../Hashtable/Hashtable.h"
#include "../String/StringBuilder.h"

void kerepTypeDescriptors_initKerepTypes(){
    // null
    kerepType_register(NULL, Null, NULL);
    // base types
    kerepType_register(char,    Char,    NULL);
    kerepType_register(bool,    Bool,    NULL);
    kerepType_register(float32, Float32, NULL);
    kerepType_register(float64, Float64, NULL);
    kerepType_register(int8,    Int8,    NULL);
    kerepType_register(uint8,   UInt8,   NULL);
    kerepType_register(int16,   Int16,   NULL);
    kerepType_register(uint16,  UInt16,  NULL);
    kerepType_register(int32,   Int32,   NULL);
    kerepType_register(uint32,  UInt32,  NULL);
    kerepType_register(int64,   Int64,   NULL);
    kerepType_register(uint64,  UInt64,  NULL);
    // base type pointers
    kerepType_register(char*,    CharPtr,    NULL);
    kerepType_register(bool*,    BoolPtr,    NULL);
    kerepType_register(float32*, Float32Ptr, NULL);
    kerepType_register(float64*, Float64Ptr, NULL);
    kerepType_register(int8*,    Int8Ptr,    NULL);
    kerepType_register(uint8*,   UInt8Ptr,   NULL);
    kerepType_register(int16*,   Int16Ptr,   NULL);
    kerepType_register(uint16*,  UInt16Ptr,  NULL);
    kerepType_register(int32*,   Int32Ptr,   NULL);
    kerepType_register(uint32*,  UInt32Ptr,  NULL);
    kerepType_register(int64*,   Int64Ptr,   NULL);
    kerepType_register(uint64*,  UInt64Ptr,  NULL);

    // base type autoarrs
    kerepType_register(Autoarr_char,    AutoarrChar,    ____Autoarr_free_char);
    kerepType_register(Autoarr_bool,    AutoarrBool,    ____Autoarr_free_bool);
    kerepType_register(Autoarr_float32, AutoarrFloat32, ____Autoarr_free_float32);
    kerepType_register(Autoarr_float64, AutoarrFloat64, ____Autoarr_free_float64);
    kerepType_register(Autoarr_int8,    AutoarrInt8,    ____Autoarr_free_int8);
    kerepType_register(Autoarr_uint8,   AutoarrUInt8,   ____Autoarr_free_uint8);
    kerepType_register(Autoarr_int16,   AutoarrInt16,   ____Autoarr_free_int16);
    kerepType_register(Autoarr_uint16,  AutoarrUInt16,  ____Autoarr_free_uint16);
    kerepType_register(Autoarr_int32,   AutoarrInt32,   ____Autoarr_free_int32);
    kerepType_register(Autoarr_uint32,  AutoarrUInt32,  ____Autoarr_free_uint32);
    kerepType_register(Autoarr_int64,   AutoarrInt64,   ____Autoarr_free_int64);
    kerepType_register(Autoarr_uint64,  AutoarrUInt64,  ____Autoarr_free_uint64);
    // base type autoarr pointers
    kerepType_register(Autoarr_char*,    AutoarrCharPtr,    ____Autoarr_free_char);
    kerepType_register(Autoarr_bool*,    AutoarrBoolPtr,    ____Autoarr_free_bool);
    kerepType_register(Autoarr_float32*, AutoarrFloat32Ptr, ____Autoarr_free_float32);
    kerepType_register(Autoarr_float64*, AutoarrFloat64Ptr, ____Autoarr_free_float64);
    kerepType_register(Autoarr_int8*,    AutoarrInt8Ptr,    ____Autoarr_free_int8);
    kerepType_register(Autoarr_uint8*,   AutoarrUInt8Ptr,   ____Autoarr_free_uint8);
    kerepType_register(Autoarr_int16*,   AutoarrInt16Ptr,   ____Autoarr_free_int16);
    kerepType_register(Autoarr_uint16*,  AutoarrUInt16Ptr,  ____Autoarr_free_uint16);
    kerepType_register(Autoarr_int32*,   AutoarrInt32Ptr,   ____Autoarr_free_int32);
    kerepType_register(Autoarr_uint32*,  AutoarrUInt32Ptr,  ____Autoarr_free_uint32);
    kerepType_register(Autoarr_int64*,   AutoarrInt64Ptr,   ____Autoarr_free_int64);
    kerepType_register(Autoarr_uint64*,  AutoarrUInt64Ptr,  ____Autoarr_free_uint64);

    // Unitype
    kerepType_register(Unitype, Unitype, __UnitypePtr_free);
    kerepType_register(Unitype*, UnitypePtr, __UnitypePtr_free);
    kerepType_register(Autoarr_Unitype,  AutoarrUnitype,  ____Autoarr_free_Unitype_);
    kerepType_register(Autoarr_Unitype*,  AutoarrUnitypePtr,  ____Autoarr_free_Unitype_);
    // replacing autogenerated freear() function to custom 
    Autoarr_Unitype* _uar=Autoarr_create(Unitype, 1, 1);
    _uar->functions->freear=__Autoarr_free_Unitype_;
    Autoarr_free(_uar, true);

    // SearchTreeNode
    kerepType_register(STNode,  STNode,    __STNode_free);
    kerepType_register(STNode*, STNodePtr, __STNode_free);

    // KeyValuePair
    kerepType_register(KVPair, KVPair, __KVPair_free);
    kerepType_register(KVPair*, KVPairPtr, __KVPair_free);
    kerepType_register(Autoarr_KVPair, AutoarrKVPair, ____Autoarr_free_KVPair_);
    kerepType_register(Autoarr_KVPair*, AutoarrKVPairPtr, ____Autoarr_free_KVPair_);
    // replacing autogenerated freear() function to custom 
    Autoarr_KVPair* _kvpar=Autoarr_create(KVPair, 1, 1);
    _kvpar->functions->freear=__Autoarr_free_KVPair_;
    Autoarr_free(_kvpar, true);

    // Hashtable
    kerepType_register(Hashtable,  Hashtable,    __Hashtable_free);
    kerepType_register(Hashtable*, HashtablePtr, __Hashtable_free);

    // StringBuilder
    kerepType_register(StringBuilder,  StringBuilder,    __StringBuilder_free);
    kerepType_register(StringBuilder*, StringBuilderPtr, __StringBuilder_free);
}
